export const SWITCH_VISUALIZATION_TYPE = 'SWITCH_VISUALIZATION_TYPE';
export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
export const SET_CHANGE_TERM = 'SET_CHANGE_TERM';
export const SUBMIT_SEARCH_TERM = 'SUBMIT_SEARCH_TERM';
export const REMOVE_SEARCH_TERM = 'REMOVE_SEARCH_TERM';

export default {
	SWITCH_VISUALIZATION_TYPE,
	TOGGLE_LEFT_SIDEBAR,
	SET_CHANGE_TERM,
	SUBMIT_SEARCH_TERM,
	REMOVE_SEARCH_TERM
};
