export const SET_CHANGE_TERM = 'SET_CHANGE_TERM';
export const SUBMIT_SEARCH_TERM = 'SUBMIT_SEARCH_TERM';
export const REMOVE_SEARCH_TERM = 'REMOVE_SEARCH_TERM';

export default {
	SET_CHANGE_TERM,
	SUBMIT_SEARCH_TERM,
	REMOVE_SEARCH_TERM
};
